<a href="https://colab.research.google.com/github/ameyyy7303/DL/blob/main/backpropagation_regression1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd

In [ ]:
df = pd.DataFrame([[3,5,2],[6,3,3],[10,7,7],[9,10,9]], columns=['rooms', 'floors', 'price'])#creating the dataset

In [ ]:
df

rooms  floors  price
0      3       5      2
1      6       3      3
2     10       7      7
3      9      10      9

In [ ]:
#Takes the architecture as i/p and create 9 trainable parameters
def initialize_parameters(layer_dims):

  np.random.seed(3)
  parameters = {}
  L = len(layer_dims)

  for l in range(1, L):

    parameters['W' + str(l)] = np.ones((layer_dims[l-1], layer_dims[l]))*0.1
    parameters['b' + str(l)] = np.zeros((layer_dims[l], 1))


  return parameters

In [ ]:
initialize_parameters([2,2,1])

{'W1': array([[0.1, 0.1],
        [0.1, 0.1]]),
 'b1': array([[0.],
        [0.]]),
 'W2': array([[0.1],
        [0.1]]),
 'b2': array([[0.]])}

In [ ]:
#used to calculate the output of the node
def linear_forward(A_prev, W, b):

  Z = np.dot(W.T, A_prev) + b

  return Z

In [ ]:
# Main Forward Propagation
def L_layer_forward(X, parameters):

  A = X
  L = len(parameters) // 2                  # number of layers in the neural network

  for l in range(1, L+1):
    A_prev = A
    Wl = parameters['W' + str(l)]
    bl = parameters['b' + str(l)]
    #print("A"+str(l-1)+": ", A_prev)
    #print("W"+str(l)+": ", Wl)
    #print("b"+str(l)+": ", bl)
    #print("--"*20)

    A = linear_forward(A_prev, Wl, bl)
    #print("A"+str(l)+": ", A)
    #print("**"*20)

  return A,A_prev #returns A2,A1

In [ ]:
X = df[['rooms', 'floors']].values[0].reshape(2,1) # Shape(no of features, no. of training example)
y = df[['price']].values[0][0]

# Parameter initialization
parameters = initialize_parameters([2,2,1])

In [ ]:
X,y

(array([[3],
        [5]]),
 np.int64(2))

In [ ]:
y_hat,A1 = L_layer_forward(X, parameters)
y_hat,A1

A0:  [[3]
 [5]]
W1:  [[0.1 0.1]
 [0.1 0.1]]
b1:  [[0.]
 [0.]]
----------------------------------------
A1:  [[0.8]
 [0.8]]
****************************************
A1:  [[0.8]
 [0.8]]
W2:  [[0.1]
 [0.1]]
b2:  [[0.]]
----------------------------------------
A2:  [[0.16]]
****************************************


(array([[0.16]]),
 array([[0.8],
        [0.8]]))

In [ ]:
(y-0.16)**2

np.float64(3.3856)

In [ ]:
y_hat

array([[0.16]])

In [ ]:
y_hat =y_hat[0][0] # as y_hat is in form of array to extract in form of a number we do this
y_hat

np.float64(0.16000000000000003)

In [ ]:
A1

array([[0.8],
       [0.8]])

In [ ]:
update_parameters(parameters,y,y_hat,A1,X)

<ipython-input-30-8094a11ecd6c>:4: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  parameters['W2'][0][0] = parameters['W2'][0][0] + (0.001 * 2 * (y - y_hat)*A1[0][0]) #Wnew=Wold-lr*derivative
<ipython-input-30-8094a11ecd6c>:5: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  parameters['W2'][1][0] = parameters['W2'][1][0] + (0.001 * 2 * (y - y_hat)*A1[1][0])
<ipython-input-30-8094a11ecd6c>:6: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  parameters['b2'][0][0] = parame

In [ ]:
parameters

{'W1': array([[0.10230551, 0.10384251],
        [0.10230551, 0.10384251]]),
 'b1': array([[0.0007685],
        [0.0007685]]),
 'W2': array([[0.105888],
        [0.105888]]),
 'b2': array([[0.109568]])}

In [ ]:
#To update weights and bias
#learning rate=0.001
def update_parameters(parameters,y,y_hat,A1,X):
  parameters['W2'][0][0] = parameters['W2'][0][0] + (0.001 * 2 * (y - y_hat)*A1[0][0]) #Wnew=Wold-lr*derivative
  parameters['W2'][1][0] = parameters['W2'][1][0] + (0.001 * 2 * (y - y_hat)*A1[1][0])
  parameters['b2'][0][0] = parameters['W2'][1][0] + (0.001 * 2 * (y - y_hat)) #bnew=bold-lr*derivative

  parameters['W1'][0][0] = parameters['W1'][0][0] + (0.001 * 2 * (y - y_hat)*parameters['W2'][0][0]*X[0][0])
  parameters['W1'][0][1] = parameters['W1'][0][1] + (0.001 * 2 * (y - y_hat)*parameters['W2'][0][0]*X[1][0])
  parameters['b1'][0][0] = parameters['b1'][0][0] + (0.001 * 2 * (y - y_hat)*parameters['W2'][0][0])

  parameters['W1'][1][0] = parameters['W1'][1][0] + (0.001 * 2 * (y - y_hat)*parameters['W2'][1][0]*X[0][0])
  parameters['W1'][1][1] = parameters['W1'][1][1] + (0.001 * 2 * (y - y_hat)*parameters['W2'][1][0]*X[1][0])
  parameters['b1'][1][0] = parameters['b1'][1][0] + (0.001 * 2 * (y - y_hat)*parameters['W2'][1][0])

In [ ]:
X = df[['rooms', 'floors']].values[1].reshape(2,1) # Shape(no of features, no. of training example)
y = df[['price']].values[1][0]

# Parameter initialization
parameters = initialize_parameters([2,2,1])

y_hat,A1 = L_layer_forward(X,parameters)
y_hat = y_hat[0][0]

update_parameters(parameters,y,y_hat,A1,X)

parameters

{'W1': array([[0.10355577, 0.10177789],
        [0.10355577, 0.10177789]]),
 'b1': array([[0.00059263],
        [0.00059263]]),
 'W2': array([[0.105076],
        [0.105076]]),
 'b2': array([[0.110716]])}

In [ ]:
X = df[['rooms', 'floors']].values[2].reshape(2,1) # Shape(no of features, no. of training example)
y = df[['price']].values[2][0]

# Parameter initialization
parameters = initialize_parameters([2,2,1])

y_hat,A1 = L_layer_forward(X,parameters)
y_hat = y_hat[0][0]

update_parameters(parameters,y,y_hat,A1,X)

parameters

{'W1': array([[0.11633618, 0.11143533],
        [0.11633618, 0.11143533]]),
 'b1': array([[0.00163362],
        [0.00163362]]),
 'W2': array([[0.122644],
        [0.122644]]),
 'b2': array([[0.135964]])}

In [ ]:
# epochs implementation

parameters = initialize_parameters([2,2,1])
epochs = 7

for i in range(epochs):

  Loss = []

  for j in range(df.shape[0]):

    X = df[['rooms', 'floors']].values[j].reshape(2,1) # Shape(no of features, no. of training example)
    y = df[['price']].values[j][0]

    # Parameter initialization


    y_hat,A1 = L_layer_forward(X,parameters)
    y_hat = y_hat[0][0]

    update_parameters(parameters,y,y_hat,A1,X)

    Loss.append((y-y_hat)**2)

  print('Epoch - ',i+1,'Loss - ',np.array(Loss).mean())

parameters

Epoch -  1 Loss -  30.331517621889077
Epoch -  2 Loss -  24.38709584229491
Epoch -  3 Loss -  15.545136281603792
Epoch -  4 Loss -  6.907302721217588
Epoch -  5 Loss -  2.5038824309036203
Epoch -  6 Loss -  1.4769617714784047
Epoch -  7 Loss -  1.4089011801308136


{'W1': array([[0.40688907, 0.38228253],
        [0.3977322 , 0.3736439 ]]),
 'b1': array([[0.03164756],
        [0.03076868]]),
 'W2': array([[0.52597424],
        [0.50165624]]),
 'b2': array([[0.50453335]])}

# **PYTORCH** **IMPLEMENTATION**

In [ ]:
import torch
import pandas as pd

# Convert entire dataset to PyTorch tensors
X = torch.tensor(df[['rooms', 'floors']].values, dtype=torch.float32)  # Shape (4, 2)
y = torch.tensor(df[['price']].values, dtype=torch.float32)  # Shape (4, 1)

In [ ]:
import torch.nn as nn
import torch.optim as optim

# Define the model
class PytorchImplementation(nn.Module):
    def __init__(self, in_features, hidden_units, out_features):
        super().__init__()
        self.layer1 = nn.Linear(in_features, hidden_units)
        self.layer2 = nn.Linear(hidden_units, out_features)

        # Manually initialize weights and biases
        nn.init.constant_(self.layer1.weight, 0.1)  # Set weights to 0.1
        nn.init.constant_(self.layer1.bias, 0.0)    # Set bias to 0
        nn.init.constant_(self.layer2.weight, 0.1)  # Set weights to 0.1
        nn.init.constant_(self.layer2.bias, 0.0)    # Set bias to 0

    def forward(self, x):
        x = self.layer1(x)
        x = self.layer2(x)
        return x

# Initialize model, loss function, and optimizer
model_0 = PytorchImplementation(in_features=2, hidden_units=2, out_features=1)
loss_fun = nn.MSELoss()
optimizer = optim.SGD(model_0.parameters(), lr=0.001)
model_0.state_dict()

OrderedDict([('layer1.weight',
              tensor([[0.1000, 0.1000],
                      [0.1000, 0.1000]])),
             ('layer1.bias', tensor([0., 0.])),
             ('layer2.weight', tensor([[0.1000, 0.1000]])),
             ('layer2.bias', tensor([0.]))])

In [ ]:
# Training loop
epochs = 7
for epoch in range(epochs):
    Loss=[]
    model_0.train()

    # Forward pass
    y_preds = model_0(X)  # Predict on all data at once
    loss = loss_fun(y_preds, y) # Compute loss

    # Backward pass
    optimizer.zero_grad()
    loss.backward()
    optimizer.step()
    Loss.append(loss.item())

    print(f"Epoch {epoch+1} | Loss: {np.array(Loss).mean()}")
# Check learned weights and biases
print("Layer 1 Weights:", model_0.layer1.weight)
print("Layer 1 Bias:", model_0.layer1.bias)
print("Layer 2 Weights:", model_0.layer2.weight)
print("Layer 2 Bias:", model_0.layer2.bias)

Epoch 1 | Loss: 32.49949645996094
Epoch 2 | Loss: 31.6094970703125
Epoch 3 | Loss: 30.572675704956055
Epoch 4 | Loss: 29.36763572692871
Epoch 5 | Loss: 27.975378036499023
Epoch 6 | Loss: 26.381973266601562
Epoch 7 | Loss: 24.582046508789062
Layer 1 Weights: Parameter containing:
tensor([[0.1830, 0.1750],
        [0.1830, 0.1750]], requires_grad=True)
Layer 1 Bias: Parameter containing:
tensor([0.0099, 0.0099], requires_grad=True)
Layer 2 Weights: Parameter containing:
tensor([[0.2345, 0.2345]], requires_grad=True)
Layer 2 Bias: Parameter containing:
tensor([0.0654], requires_grad=True)
